// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Image.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__IMAGE_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__IMAGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMAGE_SOURCE)
#define IMAGE_DllAPI __declspec( dllexport )
#else
#define IMAGE_DllAPI __declspec( dllimport )
#endif // IMAGE_SOURCE
#else
#define IMAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace builtin_interfaces {

namespace msg {

namespace dds_ {



/*!
 * @brief This class represents the structure Time_ defined by the user in the IDL file.
 * @ingroup Image
 */
class Time_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Time_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Time_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object builtin_interfaces::msg::dds_::Time_ that will be copied.
     */
    eProsima_user_DllExport Time_(
            const Time_& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object builtin_interfaces::msg::dds_::Time_ that will be copied.
     */
    eProsima_user_DllExport Time_(
            Time_&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object builtin_interfaces::msg::dds_::Time_ that will be copied.
     */
    eProsima_user_DllExport Time_& operator =(
            const Time_& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object builtin_interfaces::msg::dds_::Time_ that will be copied.
     */
    eProsima_user_DllExport Time_& operator =(
            Time_&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x builtin_interfaces::msg::dds_::Time_ object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Time_& x) const;

    /*!
     * @brief Comparison operator.
     * @param x builtin_interfaces::msg::dds_::Time_ object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Time_& x) const;

    /*!
     * @brief This function sets a value in member sec
     * @param _sec New value for member sec
     */
    eProsima_user_DllExport void sec(
            int32_t _sec);

    /*!
     * @brief This function returns the value of member sec
     * @return Value of member sec
     */
    eProsima_user_DllExport int32_t sec() const;

    /*!
     * @brief This function returns a reference to member sec
     * @return Reference to member sec
     */
    eProsima_user_DllExport int32_t& sec();


    /*!
     * @brief This function sets a value in member nanosec
     * @param _nanosec New value for member nanosec
     */
    eProsima_user_DllExport void nanosec(
            uint32_t _nanosec);

    /*!
     * @brief This function returns the value of member nanosec
     * @return Value of member nanosec
     */
    eProsima_user_DllExport uint32_t nanosec() const;

    /*!
     * @brief This function returns a reference to member nanosec
     * @return Reference to member nanosec
     */
    eProsima_user_DllExport uint32_t& nanosec();

private:

    int32_t m_sec{0};
    uint32_t m_nanosec{0};

};

} // namespace dds_

} // namespace msg

} // namespace builtin_interfaces
namespace std_msgs {

namespace msg {

namespace dds_ {



/*!
 * @brief This class represents the structure Header_ defined by the user in the IDL file.
 * @ingroup Image
 */
class Header_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Header_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Header_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object std_msgs::msg::dds_::Header_ that will be copied.
     */
    eProsima_user_DllExport Header_(
            const Header_& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object std_msgs::msg::dds_::Header_ that will be copied.
     */
    eProsima_user_DllExport Header_(
            Header_&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object std_msgs::msg::dds_::Header_ that will be copied.
     */
    eProsima_user_DllExport Header_& operator =(
            const Header_& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object std_msgs::msg::dds_::Header_ that will be copied.
     */
    eProsima_user_DllExport Header_& operator =(
            Header_&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::dds_::Header_ object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Header_& x) const;

    /*!
     * @brief Comparison operator.
     * @param x std_msgs::msg::dds_::Header_ object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Header_& x) const;

    /*!
     * @brief This function copies the value in member stamp
     * @param _stamp New value to be copied in member stamp
     */
    eProsima_user_DllExport void stamp(
            const builtin_interfaces::msg::dds_::Time_& _stamp);

    /*!
     * @brief This function moves the value in member stamp
     * @param _stamp New value to be moved in member stamp
     */
    eProsima_user_DllExport void stamp(
            builtin_interfaces::msg::dds_::Time_&& _stamp);

    /*!
     * @brief This function returns a constant reference to member stamp
     * @return Constant reference to member stamp
     */
    eProsima_user_DllExport const builtin_interfaces::msg::dds_::Time_& stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport builtin_interfaces::msg::dds_::Time_& stamp();


    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::string& _frame_id);

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::string&& _frame_id);

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::string& frame_id() const;

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::string& frame_id();

private:

    builtin_interfaces::msg::dds_::Time_ m_stamp;
    std::string m_frame_id;

};

} // namespace dds_

} // namespace msg

} // namespace std_msgs
namespace sensor_msgs {

namespace msg {

namespace dds_ {





/*!
 * @brief This class represents the structure Image_ defined by the user in the IDL file.
 * @ingroup Image
 */
class Image_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Image_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Image_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::dds_::Image_ that will be copied.
     */
    eProsima_user_DllExport Image_(
            const Image_& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::dds_::Image_ that will be copied.
     */
    eProsima_user_DllExport Image_(
            Image_&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::dds_::Image_ that will be copied.
     */
    eProsima_user_DllExport Image_& operator =(
            const Image_& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::dds_::Image_ that will be copied.
     */
    eProsima_user_DllExport Image_& operator =(
            Image_&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::dds_::Image_ object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Image_& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::dds_::Image_ object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Image_& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::dds_::Header_& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::dds_::Header_&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::dds_::Header_& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::dds_::Header_& header();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width();


    /*!
     * @brief This function copies the value in member encoding
     * @param _encoding New value to be copied in member encoding
     */
    eProsima_user_DllExport void encoding(
            const std::string& _encoding);

    /*!
     * @brief This function moves the value in member encoding
     * @param _encoding New value to be moved in member encoding
     */
    eProsima_user_DllExport void encoding(
            std::string&& _encoding);

    /*!
     * @brief This function returns a constant reference to member encoding
     * @return Constant reference to member encoding
     */
    eProsima_user_DllExport const std::string& encoding() const;

    /*!
     * @brief This function returns a reference to member encoding
     * @return Reference to member encoding
     */
    eProsima_user_DllExport std::string& encoding();


    /*!
     * @brief This function sets a value in member is_bigendian
     * @param _is_bigendian New value for member is_bigendian
     */
    eProsima_user_DllExport void is_bigendian(
            uint8_t _is_bigendian);

    /*!
     * @brief This function returns the value of member is_bigendian
     * @return Value of member is_bigendian
     */
    eProsima_user_DllExport uint8_t is_bigendian() const;

    /*!
     * @brief This function returns a reference to member is_bigendian
     * @return Reference to member is_bigendian
     */
    eProsima_user_DllExport uint8_t& is_bigendian();


    /*!
     * @brief This function sets a value in member step
     * @param _step New value for member step
     */
    eProsima_user_DllExport void step(
            uint32_t _step);

    /*!
     * @brief This function returns the value of member step
     * @return Value of member step
     */
    eProsima_user_DllExport uint32_t step() const;

    /*!
     * @brief This function returns a reference to member step
     * @return Reference to member step
     */
    eProsima_user_DllExport uint32_t& step();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data();

private:

    std_msgs::msg::dds_::Header_ m_header;
    uint32_t m_height{0};
    uint32_t m_width{0};
    std::string m_encoding;
    uint8_t m_is_bigendian{0};
    uint32_t m_step{0};
    std::vector<uint8_t> m_data;

};

} // namespace dds_

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_DDS__IMAGE_H_



