// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UpdateNotification.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "UpdateNotification.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace ota_update_interfaces {

namespace msg {

namespace dds_ {



UpdateNotification_::UpdateNotification_()
{
}

UpdateNotification_::~UpdateNotification_()
{
}

UpdateNotification_::UpdateNotification_(
        const UpdateNotification_& x)
{
    m_target = x.m_target;
    m_version = x.m_version;
    m_file_path = x.m_file_path;
    m_file_size = x.m_file_size;
}

UpdateNotification_::UpdateNotification_(
        UpdateNotification_&& x) noexcept
{
    m_target = std::move(x.m_target);
    m_version = std::move(x.m_version);
    m_file_path = std::move(x.m_file_path);
    m_file_size = x.m_file_size;
}

UpdateNotification_& UpdateNotification_::operator =(
        const UpdateNotification_& x)
{

    m_target = x.m_target;
    m_version = x.m_version;
    m_file_path = x.m_file_path;
    m_file_size = x.m_file_size;
    return *this;
}

UpdateNotification_& UpdateNotification_::operator =(
        UpdateNotification_&& x) noexcept
{

    m_target = std::move(x.m_target);
    m_version = std::move(x.m_version);
    m_file_path = std::move(x.m_file_path);
    m_file_size = x.m_file_size;
    return *this;
}

bool UpdateNotification_::operator ==(
        const UpdateNotification_& x) const
{
    return (m_target == x.m_target &&
           m_version == x.m_version &&
           m_file_path == x.m_file_path &&
           m_file_size == x.m_file_size);
}

bool UpdateNotification_::operator !=(
        const UpdateNotification_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member target
 * @param _target New value to be copied in member target
 */
void UpdateNotification_::target(
        const std::string& _target)
{
    m_target = _target;
}

/*!
 * @brief This function moves the value in member target
 * @param _target New value to be moved in member target
 */
void UpdateNotification_::target(
        std::string&& _target)
{
    m_target = std::move(_target);
}

/*!
 * @brief This function returns a constant reference to member target
 * @return Constant reference to member target
 */
const std::string& UpdateNotification_::target() const
{
    return m_target;
}

/*!
 * @brief This function returns a reference to member target
 * @return Reference to member target
 */
std::string& UpdateNotification_::target()
{
    return m_target;
}


/*!
 * @brief This function copies the value in member version
 * @param _version New value to be copied in member version
 */
void UpdateNotification_::version(
        const std::string& _version)
{
    m_version = _version;
}

/*!
 * @brief This function moves the value in member version
 * @param _version New value to be moved in member version
 */
void UpdateNotification_::version(
        std::string&& _version)
{
    m_version = std::move(_version);
}

/*!
 * @brief This function returns a constant reference to member version
 * @return Constant reference to member version
 */
const std::string& UpdateNotification_::version() const
{
    return m_version;
}

/*!
 * @brief This function returns a reference to member version
 * @return Reference to member version
 */
std::string& UpdateNotification_::version()
{
    return m_version;
}


/*!
 * @brief This function copies the value in member file_path
 * @param _file_path New value to be copied in member file_path
 */
void UpdateNotification_::file_path(
        const std::string& _file_path)
{
    m_file_path = _file_path;
}

/*!
 * @brief This function moves the value in member file_path
 * @param _file_path New value to be moved in member file_path
 */
void UpdateNotification_::file_path(
        std::string&& _file_path)
{
    m_file_path = std::move(_file_path);
}

/*!
 * @brief This function returns a constant reference to member file_path
 * @return Constant reference to member file_path
 */
const std::string& UpdateNotification_::file_path() const
{
    return m_file_path;
}

/*!
 * @brief This function returns a reference to member file_path
 * @return Reference to member file_path
 */
std::string& UpdateNotification_::file_path()
{
    return m_file_path;
}


/*!
 * @brief This function sets a value in member file_size
 * @param _file_size New value for member file_size
 */
void UpdateNotification_::file_size(
        uint64_t _file_size)
{
    m_file_size = _file_size;
}

/*!
 * @brief This function returns the value of member file_size
 * @return Value of member file_size
 */
uint64_t UpdateNotification_::file_size() const
{
    return m_file_size;
}

/*!
 * @brief This function returns a reference to member file_size
 * @return Reference to member file_size
 */
uint64_t& UpdateNotification_::file_size()
{
    return m_file_size;
}




} // namespace dds_


} // namespace msg


} // namespace ota_update_interfaces
// Include auxiliary functions like for serializing/deserializing.
#include "UpdateNotificationCdrAux.ipp"

