module builtin_interfaces {
    module msg {
        module dds_ {
            struct Time_ {
                long sec;
                unsigned long nanosec;
            };
        };
    };
};

module std_msgs {
    module msg {
        module dds_ {
            struct Header_ {
                builtin_interfaces::msg::dds_::Time_ stamp;
                string frame_id;
            };
        };
    };
};

module sensor_msgs {
    module msg {
        module dds_ {
            struct Image_ {
                std_msgs::msg::dds_::Header_ header;
                unsigned long height;
                unsigned long width;
                string encoding;
                octet is_bigendian;
                unsigned long step;
                sequence<octet> data;
            };
        };
    };
};