// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Status.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Status.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace interfaces_pkg {

namespace msg {

namespace dds_ {



SteeringStatus_::SteeringStatus_()
{
}

SteeringStatus_::~SteeringStatus_()
{
}

SteeringStatus_::SteeringStatus_(
        const SteeringStatus_& x)
{
    m_steering = x.m_steering;
}

SteeringStatus_::SteeringStatus_(
        SteeringStatus_&& x) noexcept
{
    m_steering = x.m_steering;
}

SteeringStatus_& SteeringStatus_::operator =(
        const SteeringStatus_& x)
{

    m_steering = x.m_steering;
    return *this;
}

SteeringStatus_& SteeringStatus_::operator =(
        SteeringStatus_&& x) noexcept
{

    m_steering = x.m_steering;
    return *this;
}

bool SteeringStatus_::operator ==(
        const SteeringStatus_& x) const
{
    return (m_steering == x.m_steering);
}

bool SteeringStatus_::operator !=(
        const SteeringStatus_& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member steering
 * @param _steering New value for member steering
 */
void SteeringStatus_::steering(
        int32_t _steering)
{
    m_steering = _steering;
}

/*!
 * @brief This function returns the value of member steering
 * @return Value of member steering
 */
int32_t SteeringStatus_::steering() const
{
    return m_steering;
}

/*!
 * @brief This function returns a reference to member steering
 * @return Reference to member steering
 */
int32_t& SteeringStatus_::steering()
{
    return m_steering;
}




} // namespace dds_


} // namespace msg


} // namespace interfaces_pkg
// Include auxiliary functions like for serializing/deserializing.
#include "StatusCdrAux.ipp"

