// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UpdateNotification.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_OTA_UPDATE_INTERFACES_MSG_DDS__UPDATENOTIFICATION_H_
#define _FAST_DDS_GENERATED_OTA_UPDATE_INTERFACES_MSG_DDS__UPDATENOTIFICATION_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UPDATENOTIFICATION_SOURCE)
#define UPDATENOTIFICATION_DllAPI __declspec( dllexport )
#else
#define UPDATENOTIFICATION_DllAPI __declspec( dllimport )
#endif // UPDATENOTIFICATION_SOURCE
#else
#define UPDATENOTIFICATION_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UPDATENOTIFICATION_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace ota_update_interfaces {

namespace msg {

namespace dds_ {



/*!
 * @brief This class represents the structure UpdateNotification_ defined by the user in the IDL file.
 * @ingroup UpdateNotification
 */
class UpdateNotification_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport UpdateNotification_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~UpdateNotification_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ota_update_interfaces::msg::dds_::UpdateNotification_ that will be copied.
     */
    eProsima_user_DllExport UpdateNotification_(
            const UpdateNotification_& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ota_update_interfaces::msg::dds_::UpdateNotification_ that will be copied.
     */
    eProsima_user_DllExport UpdateNotification_(
            UpdateNotification_&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ota_update_interfaces::msg::dds_::UpdateNotification_ that will be copied.
     */
    eProsima_user_DllExport UpdateNotification_& operator =(
            const UpdateNotification_& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ota_update_interfaces::msg::dds_::UpdateNotification_ that will be copied.
     */
    eProsima_user_DllExport UpdateNotification_& operator =(
            UpdateNotification_&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x ota_update_interfaces::msg::dds_::UpdateNotification_ object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const UpdateNotification_& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ota_update_interfaces::msg::dds_::UpdateNotification_ object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const UpdateNotification_& x) const;

    /*!
     * @brief This function copies the value in member target
     * @param _target New value to be copied in member target
     */
    eProsima_user_DllExport void target(
            const std::string& _target);

    /*!
     * @brief This function moves the value in member target
     * @param _target New value to be moved in member target
     */
    eProsima_user_DllExport void target(
            std::string&& _target);

    /*!
     * @brief This function returns a constant reference to member target
     * @return Constant reference to member target
     */
    eProsima_user_DllExport const std::string& target() const;

    /*!
     * @brief This function returns a reference to member target
     * @return Reference to member target
     */
    eProsima_user_DllExport std::string& target();


    /*!
     * @brief This function copies the value in member version
     * @param _version New value to be copied in member version
     */
    eProsima_user_DllExport void version(
            const std::string& _version);

    /*!
     * @brief This function moves the value in member version
     * @param _version New value to be moved in member version
     */
    eProsima_user_DllExport void version(
            std::string&& _version);

    /*!
     * @brief This function returns a constant reference to member version
     * @return Constant reference to member version
     */
    eProsima_user_DllExport const std::string& version() const;

    /*!
     * @brief This function returns a reference to member version
     * @return Reference to member version
     */
    eProsima_user_DllExport std::string& version();


    /*!
     * @brief This function copies the value in member file_path
     * @param _file_path New value to be copied in member file_path
     */
    eProsima_user_DllExport void file_path(
            const std::string& _file_path);

    /*!
     * @brief This function moves the value in member file_path
     * @param _file_path New value to be moved in member file_path
     */
    eProsima_user_DllExport void file_path(
            std::string&& _file_path);

    /*!
     * @brief This function returns a constant reference to member file_path
     * @return Constant reference to member file_path
     */
    eProsima_user_DllExport const std::string& file_path() const;

    /*!
     * @brief This function returns a reference to member file_path
     * @return Reference to member file_path
     */
    eProsima_user_DllExport std::string& file_path();


    /*!
     * @brief This function sets a value in member file_size
     * @param _file_size New value for member file_size
     */
    eProsima_user_DllExport void file_size(
            uint64_t _file_size);

    /*!
     * @brief This function returns the value of member file_size
     * @return Value of member file_size
     */
    eProsima_user_DllExport uint64_t file_size() const;

    /*!
     * @brief This function returns a reference to member file_size
     * @return Reference to member file_size
     */
    eProsima_user_DllExport uint64_t& file_size();

private:

    std::string m_target;
    std::string m_version;
    std::string m_file_path;
    uint64_t m_file_size{0};

};

} // namespace dds_

} // namespace msg

} // namespace ota_update_interfaces

#endif // _FAST_DDS_GENERATED_OTA_UPDATE_INTERFACES_MSG_DDS__UPDATENOTIFICATION_H_



